#!/bin/bash
cd submission_files
sleep 20 | condor_submit acc_svm.sub
sleep 20 | condor_submit acc_svm_weight.sub
sleep 20 | condor_submit acc_svm_smote.sub
sleep 20 | condor_submit acc_svm_adasyn.sub
sleep 20 | condor_submit acc_svm_ruspool.sub
sleep 20 | condor_submit acc_rf.sub
sleep 20 | condor_submit acc_rf_weight.sub
sleep 20 | condor_submit acc_rf_smote.sub
sleep 20 | condor_submit acc_rf_adasyn.sub
sleep 20 | condor_submit acc_rf_ruspool.sub
sleep 20 | condor_submit acc_xgboost.sub
sleep 20 | condor_submit acc_xgboost_weight.sub
sleep 20 | condor_submit acc_xgboost_smote.sub
sleep 20 | condor_submit acc_xgboost_adasyn.sub
sleep 20 | condor_submit acc_xgboost_ruspool.sub
sleep 20 | condor_submit acc_rusboost.sub
sleep 20 | condor_submit f1_svm.sub
sleep 20 | condor_submit f1_svm_weight.sub
sleep 20 | condor_submit f1_svm_smote.sub
sleep 20 | condor_submit f1_svm_adasyn.sub
sleep 20 | condor_submit f1_svm_ruspool.sub
sleep 20 | condor_submit f1_rf.sub
sleep 20 | condor_submit f1_rf_weight.sub
sleep 20 | condor_submit f1_rf_smote.sub
sleep 20 | condor_submit f1_rf_adasyn.sub
sleep 20 | condor_submit f1_rf_ruspool.sub
sleep 20 | condor_submit f1_xgboost.sub
sleep 20 | condor_submit f1_xgboost_weight.sub
sleep 20 | condor_submit f1_xgboost_smote.sub
sleep 20 | condor_submit f1_xgboost_adasyn.sub
sleep 20 | condor_submit f1_xgboost_ruspool.sub
sleep 20 | condor_submit f1_rusboost.sub
sleep 20 | condor_submit gmeans_svm.sub
sleep 20 | condor_submit gmeans_svm_weight.sub
sleep 20 | condor_submit gmeans_svm_smote.sub
sleep 20 | condor_submit gmeans_svm_adasyn.sub
sleep 20 | condor_submit gmeans_svm_ruspool.sub
sleep 20 | condor_submit gmeans_rf.sub
sleep 20 | condor_submit gmeans_rf_weight.sub
sleep 20 | condor_submit gmeans_rf_smote.sub
sleep 20 | condor_submit gmeans_rf_adasyn.sub
sleep 20 | condor_submit gmeans_rf_ruspool.sub
sleep 20 | condor_submit gmeans_xgboost.sub
sleep 20 | condor_submit gmeans_xgboost_weight.sub
sleep 20 | condor_submit gmeans_xgboost_smote.sub
sleep 20 | condor_submit gmeans_xgboost_adasyn.sub
sleep 20 | condor_submit gmeans_xgboost_ruspool.sub
sleep 20 | condor_submit gmeans_rusboost.sub
sleep 20 | condor_submit mcc_svm.sub
sleep 20 | condor_submit mcc_svm_weight.sub
sleep 20 | condor_submit mcc_svm_smote.sub
sleep 20 | condor_submit mcc_svm_adasyn.sub
sleep 20 | condor_submit mcc_svm_ruspool.sub
sleep 20 | condor_submit mcc_rf.sub
sleep 20 | condor_submit mcc_rf_weight.sub
sleep 20 | condor_submit mcc_rf_smote.sub
sleep 20 | condor_submit mcc_rf_adasyn.sub
sleep 20 | condor_submit mcc_rf_ruspool.sub
sleep 20 | condor_submit mcc_xgboost.sub
sleep 20 | condor_submit mcc_xgboost_weight.sub
sleep 20 | condor_submit mcc_xgboost_smote.sub
sleep 20 | condor_submit mcc_xgboost_adasyn.sub
sleep 20 | condor_submit mcc_xgboost_ruspool.sub
sleep 20 | condor_submit mcc_rusboost.sub
sleep 20 | condor_submit auc_svm.sub
sleep 20 | condor_submit auc_svm_weight.sub
sleep 20 | condor_submit auc_svm_smote.sub
sleep 20 | condor_submit auc_svm_adasyn.sub
sleep 20 | condor_submit auc_svm_ruspool.sub
sleep 20 | condor_submit auc_rf.sub
sleep 20 | condor_submit auc_rf_weight.sub
sleep 20 | condor_submit auc_rf_smote.sub
sleep 20 | condor_submit auc_rf_adasyn.sub
sleep 20 | condor_submit auc_rf_ruspool.sub
sleep 20 | condor_submit auc_xgboost.sub
sleep 20 | condor_submit auc_xgboost_weight.sub
sleep 20 | condor_submit auc_xgboost_smote.sub
sleep 20 | condor_submit auc_xgboost_adasyn.sub
sleep 20 | condor_submit auc_xgboost_ruspool.sub
sleep 20 | condor_submit auc_rusboost.sub
