---
title: "estudoTransformacaoDataset"
author: "Rodrigo"
date: "December 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Carregando dados
```{r}
dataset = iris

x_data = dataset[,-5]
y_data = dataset[,5]


#convertendo y_data para numerico
y_data = as.numeric(y_data)

#Binarizando os dados
x_data = x_data[-which(y_data == 3),]
y_data = y_data[-which(y_data == 3)]
y_data = droplevels(y_data)

#Transformando em 0 e 1
y_data = (y_data -2)*-1

#removendo 1 dados da primeira classe para q ela seja minoritaria
x_data = x_data[-1,]
y_data = y_data[-1]

# merge dataset
merged_dataset = cbind(x_data,y_data)
```


```{r}
imba_sample = function(x_data, y_data, minority_percent){
  
  if(length(which(y_data == 1)) < 10){
    warning("A classe minoritária nao tem observacoes suficientes.")
    return()
  }
  
  
  prob_vector = replace(replace(y_data, y_data == 1, minority_percent), y_data == 0, 1-minority_percent)

  new_dataset = merged_dataset[sample(nrow(merged_dataset), replace = TRUE, prob = prob_vector),]

  return(new_dataset)
  
}
```


#Gerando Datasets
```{r}
ds_0.05 = imba_sample(x_data, y_data, 0.05)
length(which(ds_0.05[,'y_data'] == 1))/dim(ds_0.05)[1]

ds_0.03 = imba_sample(x_data, y_data, 0.03)
length(which(ds_0.03[,'y_data'] == 1))/dim(ds_0.03)[1]

ds_0.01 = imba_sample(x_data, y_data, 0.01)
length(which(ds_0.01[,'y_data'] == 1))/dim(ds_0.01)[1]

ds_0.001 = imba_sample(x_data, y_data, 0.001)
length(which(ds_0.001[,'y_data'] == 1))/dim(ds_0.001)[1]
```

