---
title: "tuningDataBase"
author: "Rodrigo"
date: "January 3, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(3)
library(caret)
```


## Loading data
```{r}
file_path = "~/Desktop/datasets_UCI/yeast/ds_0.05.csv" 
dataset = read.csv(file_path, header=T)

x_data = dataset[,-ncol(dataset)]
y_data = dataset[,ncol(dataset)]
```


#Tuning

## Random Forest c/ Accuracy
```{r}
control = trainControl(method="repeatedcv", number=10, repeats=3, search="grid", classProbs = T)

tunegrid = expand.grid(.mtry=c(1:15))

rf_gridsearch = train(x=x_data, y=as.factor(y_data), method="parRF", metric="Accuracy", tuneGrid=tunegrid, trControl=control)

print(rf_gridsearch)
plot(rf_gridsearch)

#Métrica maxima
max(rf_gridsearch$results['Accuracy'])
```




# Estudando mLR - SVM

Definindo espaco do search
```{r}
num_ps = makeParamSet(
  makeNumericParam("C", lower = -10, upper = 10, trafo = function(x) 10^x),
  makeNumericParam("sigma", lower = -10, upper = 10, trafo = function(x) 10^x)
)
```

